language: go
go:
- '1.10'
services:
- docker
before_deploy:
- scripts/build.sh
deploy:
  - provider: releases
    api_key:
      secure: Py2jGvjm+UrN49vPWQFdWVs+yzG7xabbRQ1x8DXsT4wQ+OlGLPDKGdm7LcHcz00DdqSS5ausZKpROzAJ8kwbiidHPhFFt7zjVGTl3Hgl46CysPo5d9hM1lbjplu3iNtI3y9jqtSuZBSr6sWvCV/hqRH4oFPkZ1sxnRd8XGRsL8kwOpupIbqsQJ8DNNxfXQScS1PIqWgvTtitv/uwG57qiXYH99KArvepfB431lV6hC7DqgkiJTPDUrQCqv8u/tCsqPgE9RznDFtMax5pnOaKfWeRs+h8uanahx/0u1whonF0JBoCassHr5Isup5yRjNuh5D8wJM+rpxWSaKVtlI7oSUGVeG+W4ARfcFCPadN64IGvx4mpGlMJ9kRc0rhe5oX6vehp8KzMXvivCbGz9O6aZ2kvk7Kkfv3paC0n4vqT6hQaTKybGQ6x11eM2Ll8vFDnv3lSSVUzdM97FjVcd1W09coSA41rzYJKI3Hj7TqJEq2+ddp6j7XBsW1n0QtawHJuMFZCqNotrdJ6At0CNAGZ327LD7i8Nri28ksi3JLd9CgC7QPEdhPCMqvBFTXAc3FiYiWHBYSD1uTuYSmcRvVUlWOGMQ/y0H8aUtCYWeI2nIzrHHUWgOoR1I6acjNlr+LQ86RI4AvaaJqg+Wm0YlrP3U5VgXyWQxReaXS72BQAD4=
    file:
      - gulp-alpine
      - gulp-linux-386
      - gulp-linux-amd64
      - gulp-darwin
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
