FROM golang:alpine as goalpine

ARG BUILD_VERSION=snapshot
COPY . /go/src/github.com/thoom/gulp

WORKDIR /go/src/github.com/thoom/gulp
RUN apk add --update --no-cache git \
    && go get -d ./... \ 
    && go build -ldflags "-X github.com/thoom/gulp/client.buildVersion=$BUILD_VERSION-alpine" -o gulp-alpine

FROM alpine
LABEL author="Zach Peacock <zdp@thoomtech.com>"

RUN apk --update --no-cache add ca-certificates \
    && echo "hosts: files dns" > /etc/nsswitch.conf

COPY --from=goalpine /go/src/github.com/thoom/gulp/gulp-alpine /usr/local/bin/gulp

WORKDIR /gulp
ENTRYPOINT ["gulp"]