FROM alpine
LABEL author="Zach Peacock <zdp@thoomtech.com>"

RUN apk --update --no-cache add ca-certificates \
    && echo "hosts: files dns" > /etc/nsswitch.conf

COPY gulp-alpine /usr/local/bin/gulp

WORKDIR /gulp
ENTRYPOINT ["gulp"]